### ISSUE TITLE
File field in Directus error

### ISSUE THREAD

**Issue by kieranwt94** [Jonesus/gatsby-source-directus7#18]
There appears to be an issue with the gatsby source plugin for Directus 7 if the table has a 'file' field and it is an optional field e.g. the row doesn't need to have an image (file) but can.

**Comment by Jonesus** [comment]
Hi @kieranwt94 ! Do you think you could provide a bit more details on your problem, like a step-by-step reproduction, error messages and/or a database dump of the problematic configuration so that it's easier for me to reproduce the issue?

**Comment by westhouseit** [comment]
Here's the logs I get:

`GSD7: success Connected to Directus!`
`GSD7: success Logged in to Directus!`
`GSD7: info Fetching Directus file data...`
`error `

`GSD7: error gatsby-source-directus: Error while fetching files:  undefined`

`See our docs page for more info on this error: https://gatsby.dev/issue-how-to`
`GSD7: success Found 0 files from Directus.`


Any thoughts on enabling more detailed logging?

**Comment by westhouseit** [comment]
Done some checking in the source - this error is from fetch.js line 188. Error is returned as undefined so either `this.client.get` is failing. It looks likely to be something upstream that isn't returning a proper exception/error since this.client is DirectusSDK coming from '@directus/sdk-js'.

I'll cross-post this there: https://github.com/directus/sdk-js/issues/116

**Comment by Jonesus** [comment]
Hi @westhouseit!

Sorry for the long silence, I've been quite busy with other stuff recently. As for the issue, a new official plugin has been created at https://github.com/directus/gatsby-source, and thus this project won't be maintained anymore. You should go try it out instead and see if it works out for you and if not, open a new issue in that repo :)
