### ISSUE TITLE
Relationships recursive in graphql

### ISSUE THREAD

**Issue by pgegenfurtner** [Jonesus/gatsby-source-directus7#5]
In directus I have the following tables:

Customer: has a name(string) and projects(many-to-one) field.
Project: has a name(string) and customer(int) field.

When I query allDirectusCustomer in graphql, a recursion with customers and projects occurs. The same thing happens with m2m relationshiops.

<img width="1680" alt="Bildschirmfoto 2019-03-11 um 16 25 35" src="https://user-images.githubusercontent.com/19979167/54135891-f6163600-441a-11e9-8804-fc39ac0615e3.png">

**Comment by Jonesus** [comment]
Yeah this is something I've noticed too, but I'm not sure if it's possible to implement the relation both ways so that it would not be recursive? Such that one is able to get projects via customers but also customers via project.

I feel that this is not a major issue, as by the GraphQL implementation the recursion is only via references and thus shouldn't cause any performance concerns. It is a bit confusing to the user, though.
